[package]
name = "weld_ast"
version = "0.1.0"
authors = ["Matei Zaharia <matei.zaharia@gmail.com>"]

[lib]
path = "lib.rs"

[dependencies]
lazy_static = "0.2.1"
regex = "*"
weld_error = { path = "../weld_error", version = "^0.1.0" }
